server:
  port: 8092

spring:
  application:
    name: wooread-gateway
  cloud:
    gateway:
        routes:
          - id: generate-token
            uri: lb://wooread-user
            predicates:
              - Path=/wooread-user/generateJwtToken
            filters:
              - StripPrefix=1

          - id: register
            uri: lb://wooread-user
            predicates:
              - Path=/wooread-user/createUser
            filters:
              - StripPrefix=1

          - id: wooread-novel
            uri: lb://wooread-novel
            predicates:
              - Path=/wooread-novel/**
            filters:
              - StripPrefix=1
              - JwtToken

          - id: wooread-user
            uri: lb://wooread-user
            predicates:
              - Path=/wooread-user/**
            filters:
              - StripPrefix=1
              - JwtToken
# 这个配置在当前的spring gateway版本中有问题，使用Java配置在启动类中了
#        globalcors:
#          corsConfigurations:
#            '[/**]':
#              allowedOrigins: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.9:8761/eureka/
  instance:
    hostname: 192.168.1.9